spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xzhb
    #jdbc数据库链接 格式为：jdbc:mysql://数据库服务器地址:端口/数据库名
    username: root
    #数据库账号
    password: 123456
    #数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库驱动名

  application:
    name: StuBeacon  # 冒号后添加空格

  ai:
    openai:
      api-key: sk-70IYbwgxXqWTpXUFeHf9GrATKKeDLpcrtQj6RYigzrOBzXUN # 填写实际的API密钥
      base-url: https://xiaoai.plus #路径
  #      chat:
  #        options:
  #          model:   #gpt-4-32k 版本  32k参数
  #          temperature: #0.4F 越高准确率越低，但是创新性增加

  # 配置静态资源路径
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:${file.upload-dir}  # 将上传目录设为静态资源

# 文件上传配置
file:
  upload-dir: ./uploads  # 上传目录路径（相对项目根目录）


server:
  servlet:
    session:
      timeout: 1s

